In [22]:
import os
import time
import pandas as pd
from tqdm import tqdm 
import sys
pd.options.display.max_columns = 500

In [27]:
path_dir='E:/incheon/'
file_list = os.listdir(path_dir)

In [31]:
temp = pd.DataFrame()
for i in tqdm(file_list):
    df = pd.read_csv(path_dir+i, encoding='UTF-8', sep="|", error_bad_lines=False)
    df['YMD']=i[7:15]
    df=df.dropna(axis=0)
    temp = pd.concat([df,temp])
temp.to_csv('E:/incheon/parcel_'+str(temp.shape[0])+'.csv', mode='a', sep="|")

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 306/306 [03:54<00:00,  1.31it/s]

In [32]:
temp.head()

,Unnamed: 0,REGI_POCD,PO_NM,ZIP_CD,PO_ADDR,REGI_NO,REC_ADDR_SEQ,WGHT,VOL,경도,위도,YMD
15,15,40013,서인천우체국,22713,인천광역시 서구 서곶로 318 (심곡동),6.865151e+12,2.021110e+15,2000.0,60.0,126.665392,37.518077,20211102
16,16,40013,서인천우체국,22713,인천광역시 서구 서곶로 318 (심곡동),6.865151e+12,2.021110e+15,2000.0,60.0,126.631496,37.527216,20211102
17,17,40013,서인천우체국,22713,인천광역시 서구 서곶로 318 (심곡동),6.865151e+12,2.021110e+15,2000.0,60.0,126.668336,37.534169,20211102
18,18,40013,서인천우체국,22713,인천광역시 서구 서곶로 318 (심곡동),6.865151e+12,2.021110e+15,2000.0,60.0,126.631496,37.527216,20211102
19,19,40013,서인천우체국,22713,인천광역시 서구 서곶로 318 (심곡동),6.865152e+12,2.021110e+15,2000.0,60.0,126.676204,37.519568,20211102

In [37]:
temp['YMD']=pd.to_datetime(temp['YMD'],format="%Y%m%d")

In [38]:
temp.head()

,Unnamed: 0,REGI_POCD,PO_NM,ZIP_CD,PO_ADDR,REGI_NO,REC_ADDR_SEQ,WGHT,VOL,경도,위도,YMD
15,15,40013,서인천우체국,22713,인천광역시 서구 서곶로 318 (심곡동),6.865151e+12,2.021110e+15,2000.0,60.0,126.665392,37.518077,2021-11-02
16,16,40013,서인천우체국,22713,인천광역시 서구 서곶로 318 (심곡동),6.865151e+12,2.021110e+15,2000.0,60.0,126.631496,37.527216,2021-11-02
17,17,40013,서인천우체국,22713,인천광역시 서구 서곶로 318 (심곡동),6.865151e+12,2.021110e+15,2000.0,60.0,126.668336,37.534169,2021-11-02
18,18,40013,서인천우체국,22713,인천광역시 서구 서곶로 318 (심곡동),6.865151e+12,2.021110e+15,2000.0,60.0,126.631496,37.527216,2021-11-02
19,19,40013,서인천우체국,22713,인천광역시 서구 서곶로 318 (심곡동),6.865152e+12,2.021110e+15,2000.0,60.0,126.676204,37.519568,2021-11-02